services:
  frontend:
    build:
      context: .
      dockerfile: front
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    restart: always
    networks:
      - net
    container_name: frontend

  backend:
    build: 
      context: .
      dockerfile: back
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend
    restart: always
    networks:
      - net
    container_name: backend

networks:
  net:
    driver: bridge